### ISSUE TITLE
Quantum Jars issues

### ISSUE THREAD

**Issue by blaisen** [theflogat/Technomancy#145] opened 2015-08-24 19:17 UTC
Issues: General issues with jar labels, including: breaking empty, label-less jars, which, when placed down, inexplicably acquire random labels; incompatibility with Thaumic Tinkerer's Essentia Funnels, and the labels on jars changing when they're picked up.

**Comment by blaisen** [comment] 2015-08-24 19:25
Oh, and they don't stack when empty, but I don't know if that's a bug or a feature.

**Comment by Mordenkainen** [comment] 2015-08-25 03:37
So Thaumic Tinkerers funnel is written in such a way that it looks specifically for a Thaumcraft Jar. There isn't much that can be done about that:
https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/develop/src/main/scala/com/nekokittygames/Thaumic/Tinkerer/common/tiles/TileFunnel.scala#L161

I have confirmed the stacking issue. I'm gonna guess that they don't stack because of the saved data from when it was placed in the world. This is more of a general issue with several Technomancy blocks that will need to be looked at in the future.

I am unable to recreate any of the label issues though.

**Comment by blaisen** [comment] 2015-08-25 12:46
Thank you for looking into the funnel issue; I've opened a thread on their github. As for the stacking issue, I'm glad to hear that it's going to be looked into, and look forward to seeing it fixed.

Regarding the label issue, anything you would like me to do to help you recreate it, or?

**Comment by Mordenkainen** [comment] 2015-08-25 13:09
If you can come up with a set of steps that reliably recreates the issue that would help.

That said, it may be a moot point. My suspicion is that you probably only see these issues with jars that have been placed in the world and then picked up. If this is the case, the real issue is that IIRC Quantum Jars are supposed to be destroyed if you try picking them up.

**Comment by blaisen** [comment] 2015-08-25 13:42
In that case the issue is that I'm using Silk Touch.

**Comment by blaisen** [comment] 2015-08-25 13:51
Here's the thread I opened on Thaumic Tinkerer's Github. Hopefully this can be resolved. 

https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/779

**Comment by nekosune** [comment] 2015-08-25 13:52
@Mordenkainen Seeing as you don't do what most other mods do, and inherit from Thaumcraft's warded jars. or even implement any Thaumcraft API on that block, the only way another mod COULD know to insert into your jars, are through hard coding support for that one jar

**Comment by Mordenkainen** [comment] 2015-08-25 14:22
@nekosune

Technically what most other mods do, including this one in many cases but not this particular one, is considered bad practice since the classes involved are not part of Thaumcrafts API.

I believe the right solution would be to update your funnel to look for the IAspectContainer interface, which could easily be added to our jar.

Alternatively, you could add your own "IContainEssentia" interface, that would allow mod blocks to "opt-in" to support.

**Comment by nekosune** [comment] 2015-08-25 14:35
@Mordenkainen That is the reason most mods that add jars use a debonned thaumcraft, rather then just the api. and as I Believe allready pointed out, IAspectContainer does NOT just apply to jars, which would make at the very least rendering .... difficult, to use, To be perfectly blunt, this is the first mod's essentia jar that doesnt work, I will be in 1,8 Adding in a way to opt in, if I can think of an easy  way to let it opt in to take over the rendering of the item in funnel too.

**Comment by Mordenkainen** [comment] 2015-08-25 14:40
I havent actually seen the funnel in action. What sort of rendering support does it require?

**Comment by nekosune** [comment] 2015-08-25 14:43
Basically when provided with the item, it renders the block form in the centre, with the essentia level lowering slowly. with just jars, it is sufficient to just render a plain TC jar, with the essentia level, the trouble is if start adding more container types, would need to have a way to say "oh no rendering, or , render the level in this way instead" 1.8 with it's models and blockstates  makes this more difficult, although I hear later 1.8 / 1.9 may make that easier again

**Comment by jonabrv1965** [comment] 2015-10-12 18:29
Hi Mordekainen, I'm enjoying your fantastic mod, but found a glitch with the Quantum Jars... Since the first time I installed your mod  the Quantum Jars did not show (and doesn´t do right now) it´s contents within the inventory GUI (in contrast the warded jars do show its contents when the mouse hover it).Not a big deal, I were able to determine the Quantum jars contents via WAILA, but for a not known reason, right now WAILA is not showing the contents either!! so now I'm basically "blind", I can recognize the essentia by its color, but is a "best guess" and for example cannot differentiate between Lux and Aer... What I'm doing wrong? any advice greatly appreciated..

**Comment by Mordenkainen** [comment] 2015-10-12 19:34
Well, first off, I just help with the mod, I am not the author.

Technomancy does not have any code to display the contents of the jars.

As you stated it does not display the contents in the same way as a standard warded jar in your inventory. If I remember correctly,  when you hover the mouse over it, it should display something like "hold shift for more info" and if you do that, "hold A for aspects". Holding both "shift" and "a" should display the contents.

When placed in the world, the jars rely on the default code for displaying jars. If I remember correctly, this requires you to be wearing Goggles of Revealing or the equivalent before it will display.

**Comment by kysler** [comment] 2015-11-25 17:07
I also have the issue with labels. They can randomly change what aspect the label is filtering if placed into an inventory containing another filtered jar (can be a normal warded jar) and will even keep a filter for the previous label placed on it after removal. You can dupe labels for ever by placing a QJ with some amount of essentia and placing a label on it, remove the label then break with a terra shatterer from Botania (maybe other picks as well have we not tried) place it down and the label will reappear, remove the label again and rinse repeat. Have only been using them with Thaumic Pipes so no issues other than the labels. Not a big deal but yea this is for sure a thing that happens every time and can be done by any of  the 3 of us playing on my server without fail.

**Comment by theflogat** [comment] 2015-11-25 17:30
We'll look for a way to fix this. This is not a simple issue and may take some time to be fixed.

**Comment by Mordenkainen** [comment] 2015-11-25 17:44
I have a few days off work so I intend to look at this over the next few days.

**Closed** 2015-12-01 04:56 UTC
