### ISSUE TITLE
Severe problem report to mod owner

### ISSUE THREAD

**Issue by supercrasher** [theflogat/Technomancy#175] opened 2015-12-27 17:13 UTC
I tried to install Technomancy in ftb direwolf20 1.7.10 so that I can have these cool stuff in my world there but whenever I activate this mod I get this crash report
[crash-2015-12-27_19.09.19-client.txt](https://github.com/theflogat/Technomancy/files/72754/crash-2015-12-27_19.09.19-client.txt)

**Comment by theflogat** [comment] 2015-12-28 12:21
Either a mod has an outdated AE2 API or our API is outdated. I suspect the latter. Try to have Technomancy load in last and in first to see if that fixes it.

**Comment by Mordenkainen** [comment] 2015-12-28 17:58
Actually, there appears to be an error from AppliedAerodynamics

**Comment by Mordenkainen** [comment] 2015-12-28 18:22
In fact this commit seems to be a fix for the issue: https://github.com/thatsIch/IntelliE/commit/e3974e368a6677353dedd10780d95a9950efbd87

Perhaps try updating IntelliE?

**Comment by Mordenkainen** [comment] 2016-01-20 21:48
Closing due to lack of updates from the user reporting the issue. I suspect the issue was caused by a different mod.

**Closed by Mordenkainen** 2016-01-20 21:48 UTC
