### ISSUE TITLE
Issue with MFR? (I think)

### ISSUE THREAD

**Issue by warplord** [theflogat/Technomancy#176] opened 2016-01-19 21:36 UTC
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/19/16 6:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Expecting a stackmap frame at branch target 52
Exception Details:
Location:
powercrystals/minefactoryreloaded/MineFactoryReloadedClient.renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V @14: ifnull
Reason:
Expected stackmap frame at this location.
Bytecode:
0x0000000: b801 88b4 023e 4d2c b402 6eb6 0274 c600
0x0000010: 262c b402 6eb6 0274 b602 7ab2 0372 b602
0x0000020: 1b9a 0014 2cb4 026e b602 74b6 027a c103
0x0000030: 749a 0004 b12c b403 782c b403 7b2c b403
0x0000040: 7867 2bb4 0380 8d6b 6390 7646 2cb4 0383
0x0000050: 2cb4 0386 2cb4 0383 672b b403 808d 6b63
0x0000060: 9076 3804 2cb4 0389 2cb4 038c 2cb4 0389
0x0000070: 672b b403 808d 6b63 9076 3805 0404 0404
0x0000080: b803 9011 0bc0 b802 9b11 0b60 b802 9811
0x0000090: 0b44 b802 9b11 0be2 b802 9b11 0302 1103
0x00000a0: 03b8 0393 110d e1b8 0298 111d 00b8 0295
0x00000b0: b202 4ab9 0397 0100 3a06 1906 b903 9c01
0x00000c0: 0099 0083 1906 b903 a001 00c0 03a2 3a07
0x00000d0: 1907 c003 a4b6 03a7 9900 06a7 ffdf 2a19
0x00000e0: 07b9 03ab 0100 b603 b014 03b1 b703 b638
0x00000f0: 082a 1907 b903 ab01 00b6 03b9 1403 bab7
0x0000100: 03b6 3809 2a19 07b9 03ab 0100 b603 be14
0x0000110: 03bf b703 b638 0ab8 02ce 1708 1709 170a
0x0000120: 1303 c1b8 02d2 2517 0417 05b8 02dc 1907
0x0000130: b903 ab01 00b6 03c5 b603 cbb8 03cf b802
0x0000140: f9a7 ff79 110d e1b8 029b b1 
Stackmap Table:
append_frame(@36,Object[#618])
same_frame(@53)
full_frame(@186,{Object[#2],Object[#893],Object[#618],Float,Float,Float,Object[#921]},{})
append_frame(@222,Object[#930])
chop_frame(@324,2)

at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 52
Exception Details:
Location:
powercrystals/minefactoryreloaded/MineFactoryReloadedClient.renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V @14: ifnull
Reason:
Expected stackmap frame at this location.
Bytecode:
0x0000000: b801 88b4 023e 4d2c b402 6eb6 0274 c600
0x0000010: 262c b402 6eb6 0274 b602 7ab2 0372 b602
0x0000020: 1b9a 0014 2cb4 026e b602 74b6 027a c103
0x0000030: 749a 0004 b12c b403 782c b403 7b2c b403
0x0000040: 7867 2bb4 0380 8d6b 6390 7646 2cb4 0383
0x0000050: 2cb4 0386 2cb4 0383 672b b403 808d 6b63
0x0000060: 9076 3804 2cb4 0389 2cb4 038c 2cb4 0389
0x0000070: 672b b403 808d 6b63 9076 3805 0404 0404
0x0000080: b803 9011 0bc0 b802 9b11 0b60 b802 9811
0x0000090: 0b44 b802 9b11 0be2 b802 9b11 0302 1103
0x00000a0: 03b8 0393 110d e1b8 0298 111d 00b8 0295
0x00000b0: b202 4ab9 0397 0100 3a06 1906 b903 9c01
0x00000c0: 0099 0083 1906 b903 a001 00c0 03a2 3a07
0x00000d0: 1907 c003 a4b6 03a7 9900 06a7 ffdf 2a19
0x00000e0: 07b9 03ab 0100 b603 b014 03b1 b703 b638
0x00000f0: 082a 1907 b903 ab01 00b6 03b9 1403 bab7
0x0000100: 03b6 3809 2a19 07b9 03ab 0100 b603 be14
0x0000110: 03bf b703 b638 0ab8 02ce 1708 1709 170a
0x0000120: 1303 c1b8 02d2 2517 0417 05b8 02dc 1907
0x0000130: b903 ab01 00b6 03c5 b603 cbb8 03cf b802
0x0000140: f9a7 ff79 110d e1b8 029b b1 
Stackmap Table:
append_frame(@36,Object[#618])
same_frame(@53)
full_frame(@186,{Object[#2],Object[#893],Object[#618],Float,Float,Float,Object[#921]},{})
append_frame(@222,Object[#930])
chop_frame(@324,2)

at powercrystals.minefactoryreloaded.net.ClientProxy.init(ClientProxy.java:15)
at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.init(MineFactoryReloadedCore.java:621)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
... 10 more

Here is a crash I receive when I added Technomancy in a modpack that has MFR in it. Any ideas?

**Comment by Mordenkainen** [comment] 2016-01-20 21:47
Duplicate of #174

As soon as I get the chance I will try to add a config entry to disable the MFR integration until I can sort out the source of the issue.

Closing as a duplicate, watch for updates under #174

**Closed by Mordenkainen** 2016-01-20 21:47 UTC
