### ISSUE TITLE
Crashing with 10i (10j too)

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [theflogat/Technomancy#80] opened 2015-05-10 19:58 UTC
Latest version crashes:

http://hastebin.com/izoxogisic.vhdl

10h works just fine.

**Comment by theflogat** [comment] 2015-05-11 16:11
I'd like a little more details on how this happened.

**Comment by theflogat** [comment] 2015-05-11 16:37
The rendering bug should be fixed with the new version

**Comment by Unrepentant-Atheist** [comment] 2015-05-11 17:22
Open the book, go to Technomancy tab, boom.

**Comment by ShawnRHayes** [comment] 2015-05-11 18:02
confirmed .10j still crashes on tab

**Comment by Unrepentant-Atheist** [comment] 2015-05-11 19:52
Aye. 10j still crashing.

**Comment by Mordenkainen** [comment] 2015-05-11 20:05
Last time this was due to the removal of the Coil Coupler as a Thaumcraft recipe but leaving a reference to the Thaumcraft recipe handler for it in a Thaumonomicon entry. But I don't think any of the recipes or research entries were changed here. 

Hmmm. Could one of you post your Technomancy config file?

**Comment by Mordenkainen** [comment] 2015-05-11 20:21
NEVERMIND! Found the issue. My bad.

theflogat, I will push a fix tonight.

To all users suffering from the issue. set the "scepter=" line in your technomancy.cfg to false. "scepter=false"
This will prevent the crash.

**Closed** 2015-05-12 17:23 UTC
